# General functions

In [1]:
import numpy as np


In [2]:
arr1=np.array([[1,2,3],[2,4,3.6]])

In [3]:
print(arr1)

[[1.  2.  3. ]
 [2.  4.  3.6]]


In [4]:
timeit(arr1)

79.2 ns ± 10.1 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [5]:
arr1.shape

(2, 3)

In [6]:
arr1.dtype

dtype('float64')

In [7]:
np.zeros((4,6)).dtype

dtype('float64')

In [8]:
np.empty((4,4)).dtype

dtype('float64')

In [9]:
np.ones((6,6)).dtype

dtype('float64')

# Slicing

In [10]:
arr2=np.array([1,2,23,3])

In [11]:
print(arr2)

[ 1  2 23  3]


In [12]:
arr2.shape

(4,)

In [13]:
arr3=arr2[1:3].copy()

In [14]:
arr3

array([ 2, 23])

In [15]:
arr3[0]=9

In [16]:
arr3

array([ 9, 23])

In [17]:
arr2

array([ 1,  2, 23,  3])